### ISSUE TITLE
Signature Exception on Apache behind Nginx proxy

### ISSUE THREAD

**Issue by Failure404** [nextcloud/social#375]
Hi,
this has been discussed before in #269 but I still get this error and I am a bit lost with troubleshooting this.
`Warning: 500 - {"status":-1,"exception":"OCA\\Social\\Exceptions\\SignatureException","message":"signature cannot be checked"}
POST /index.phpal/inbox
from 163.172.251.107 at 2019-01-24T15:14:56+01:00`
Any help would be greatly appreciated.

**Comment by daita** [comment]
You should check if the local time of your server

**Comment by Failure404** [comment]
...is correct?
Yes it is. It gets synced with ntp.org. After a manual sync it corrected an offset of 0.602562 sec.
So that is not the cause.

**Comment by daita** [comment]
Can you describe what you are trying to do and where the log you pasted is coming from ?

**Comment by Failure404** [comment]
Yes of course.
I am trying to get the social app working on my Nextcloud 15.0.2 running on an Apache behind an Nginx reverse proxy on a Debian Jessie system.
For testing I am trying to "follow" the nextcloud account on mastodon.xyz. I can see this account being followed, but no posts or anything else is coming in.
In my nextcloud log I can see the following appearing over and over again:
`[no app in context] Warning: 500 - {"status":-1,"exception":"OCA\\Social\\Exceptions\\SignatureException","message":"signature cannot be checked"}
POST /index.phpal/inbox
from 163.172.251.107 at 2019-01-25T12:50:03+01:00`
163.172.251.107 resolves to mastodon.xyz. So apparently 163.172.251.107 tries to post something on my nextcloud which gets rejected by nextcloud with the quoted error.
My Apache log shows:
`2019-01-25 12:59:34 | Error | 163.172.251.107 | 500 | POST /apps/social/inbox HTTP/1.0 |`

**Comment by Failure404** [comment]
It just occurs to me... could this have to do something with the fact that I am using "pretty URLs"?
`POST /index.phpal/inbox` in my nextcloud log, and
`POST /apps/social/inbox` in my apache log

**Comment by Failure404** [comment]
Nope, that must be a weird nextcloud logging bug.
However, after a reset of the social app the error message at least contains my name now.
`{"reqId":"XEs701VyjHQAAAYhTwkAAAAJ","level":2,"time":"2019-01-25T17:39:47+01:00","remoteAddr":"163.172.251.107","user":"--","app":"no app in context","method":"POST","url":"/index.phpal/@Failure404/inbox","message":"500 - {\"status\":-1,\"exception\":\"OCA\\\\Social\\\\Exceptions\\\\SignatureException\",\"message\":\"signature cannot be checked\"}","userAgent":"http.rb/3.3.0 (Mastodon/2.7.0; +https://mastodon.xyz/)","version":"15.0.2.0","id":"5c4b3bd3d1746"}`

**Comment by daita** [comment]
I don't understand why it is ending by `.phpal`

**Comment by daita** [comment]
I got an error on your cloud itself now :(

**Comment by Failure404** [comment]
Seems like my Fail2ban didn't like your user agent ;-)
Please try again.

**Comment by daita** [comment]
So, I can send a command line curl request to your webfinger from my work station, but it is timing out from my dev env (not the same IP)

**Comment by Failure404** [comment]
Timing out from 163.xxx.xxx.xxx ?
That should also be fixed now.
Sorry for the trouble, after 25 years of Internet my ban hammer has become quite large and bans everything which smells like trouble.

**Comment by daita** [comment]
no, 91.121.xxx.xxx or 91.134.xxx.xxx

**Comment by Failure404** [comment]
Fixed :-)

**Comment by daita** [comment]
blocked once again, after few requests. This could be the issue

**Comment by Failure404** [comment]
No,
it doesn't like empty user agents. Your last request didn't have a user agent set.
I have temporarily disabled this.

**Comment by daita** [comment]
So, I can search for an account, I guess we can say that the app is well configured. 
But when I want to follow your account I got a timeout. Could it be an issue with your firewall (again) ?

**Comment by daita** [comment]
nevermind, even command line curl request times-out:

maxence@stealth:~$ curl -H "Accept: application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"" -X GET  https:\/\/cloud.[example.net]/apps\/social\/@Failure404 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0curl: (7) Failed to connect to cloud.[example.net] port 443: Connection timed out

**Comment by daita** [comment]
nevermind, even command line curl request times-out:

```
maxence@stealth:~$ curl -H "Accept: application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"" -X GET  https:\/\/cloud.[example.net]/apps\/social\/@Failure404 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0curl: (7) Failed to connect to cloud.[example.net] port 443: Connection timed out
```

I am starting to think that the issue is from your network !

**Comment by Failure404** [comment]
I can see your attempts, all GETs seem to work ok but all POSTs result either in
"OCA\\\\Social\\\\Exceptions\\\\InvalidOriginException"
or
"OCA\\\\Social\\\\Exceptions\\\\SignatureException"

**Comment by daita** [comment]
I would need more details about this, like:

- set `'loglevel'` to 1 in config.php
- reset everything using `./occ social:reset`
- send a message to your local account from a remote account (mastodon ?)

Send me all lines related to the social app in your `data/nextcloud.log`: maxence@nextcloud.com

**Comment by daita** [comment]
I would assumed it is fixed as I haven't got any feedback

**Comment by Failure404** [comment]
It's not fixed. I simply gave up on it. I couldn't provide any more info than I already did.
I went to a full blown Mastodon instance instead. This here is too pre-alpha for me.
