### ISSUE TITLE
Webfinger does not work for existing users after upgrade to 0.2.2

### ISSUE THREAD

**Issue by lachmanfrantisek** [nextcloud/social#570]
I probably messed some problems with #559, but it is probably not related. So I am creating a new issue.

Again, thank you for your time and work!

### Steps to reproduce

1. Try to call webfinger url  (`.well-known/webfinger?resource=acct:user@my.nextcloud`) for user created before upgrade.
2. Try to call account url in "Private window" of Firefox (`/apps/social/@user`) for user created before upgrade.

### Expected behaviour
1. I get JSON response for existing (old) users.
2. I get account info for existing (old) users.

### Actual behaviour
1. I get  `404` for existing users.
2. I can see only loading wheel and error "Failed to load account details user".

## Server configuration detail

**Operating system:** Linux 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64

**Webserver:** nginx/1.15.12 (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit

**PHP version:** 

7.3.5
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, gd, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, Phar, exif, ftp, gmp, imap, intl, ldap, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, zip, imagick, redis, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.1 - 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** hoellen/nextcloud docker image

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - apporder: 0.7.1
 - audioplayer: 2.7.0
 - bruteforcesettings: 1.3.0
 - calendar: 1.7.0
 - camerarawpreviews: 0.7.0
 - carnet: 0.16.1
 - circles: 0.17.3
 - cloud_federation_api: 0.2.0
 - cms_pico: 0.9.8
 - comments: 1.6.0
 - contacts: 3.1.1
 - cospend: 0.1.0
 - data_request: 1.3.0
 - dav: 1.9.2
 - deck: 0.6.2
 - drawio: 0.9.3
 - drop_account: 0.1.0
 - dropit: 0.2.1
 - event_update_notification: 0.3.4
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_3d: 0.1.0
 - files_downloadactivity: 1.5.0
 - files_external: 1.7.0
 - files_linkeditor: 1.0.10
 - files_markdown: 2.0.6
 - files_mindmap: 0.0.13
 - files_pdfviewer: 1.5.0
 - files_readmemd: 1.0.4
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - forms: 1.0.3
 - gallery: 18.3.0
 - gpxedit: 0.0.11
 - gpxmotion: 0.0.9
 - gpxpod: 3.0.3
 - groupfolders: 4.0.2
 - guests: 1.0.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - music: 0.9.5
 - nextcloud_announcements: 1.5.0
 - notes: 2.6.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - ownbackup: 19.5.0
 - password_policy: 1.6.0
 - passwords: 2019.6.0
 - polls: 0.10.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - qownnotesapi: 19.4.0
 - quota_warning: 1.5.0
 - ransomware_detection: 0.5.1
 - ransomware_protection: 1.4.0
 - recommendations: 0.4.0
 - registration: 0.4.6
 - richdocuments: 3.3.8
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - sharerenamer: 2.6.0
 - social: 0.2.2 (current master)
 - spreed: 6.0.1
 - survey_client: 1.4.0
 - suspicious_login: 1.0.0
 - systemtags: 1.6.0
 - tasks: 0.10.1
 - telephoneprovider: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_nextcloud_notification: 1.1.1
 - twofactor_totp: 2.1.2
 - twofactor_u2f: 3.0.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - checksum
 - deck.old
 - encryption
 - end_to_end_encryption
 - phonetrack
 - support
 - twofactor_admin
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "apps_paths": [
        {
            "path": "\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [***REMOVED SENSITIVE VALUE**
    ],
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE**",
    "overwriteprotocol": "https",
    "dbtype": "pgsql",
    "version": "16.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Prague",
    "logdateformat": "Y-m-d H:i:s",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "has_rebuilt_cache": true
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0

**Operating system:** Fedora Workstation 30 (Gnome)

## Logs

<details><summary>Nextcloud log</summary>

```
1)
[no app in context] Info: Exception on webfinger - Unknown account 'user'

GET /.well-known/webfinger?resource=acct:user@my.nextcloud
from 172.19.0.6 at 2019-06-04T21:50:23+02:00

2)

[lib] Error: ResourceLocator can not find a web root (root: /apps2/social, file: css/social/16ca-eb12-style.css?v=4275fa50e004d2516f6ad41a8aca8f29, webRoot: , throw: true)

GET /apps/social/@user
from 172.19.0.6 at 2019-06-04T21:51:32+02:00
```
</details>

**Comment by lachmanfrantisek** [comment]
It does not work even in the profile page (`scoutadmin` is old user, `tester` is the new user):

![Snímek z 2019-06-04 22-04-14](https://user-images.githubusercontent.com/20214043/58910138-12bdc380-8715-11e9-9d83-8b74cc897fd0.png)
![Snímek z 2019-06-04 22-03-58](https://user-images.githubusercontent.com/20214043/58910139-12bdc380-8715-11e9-85e9-c9e02ddbd575.png)

**Comment by daita** [comment]
is it fixed in 0.2.3 ?

**Comment by daita** [comment]
Can you check if the entries of your local users in the table _'oc_social_a2_cache_actors'_ have the _'local'_ field set to _true_ ?

**Comment by lachmanfrantisek** [comment]
No, they have `False`...

Do I need to set them manually? Nevertheless, there should be some problem with the migration.

**Comment by lachmanfrantisek** [comment]
When I change the value to True, webfinger endpoint and profile page work well.

**Comment by lachmanfrantisek** [comment]
It can be easily fixed by one query. Something like this:

```
update oc_social_a2_cache_actors set local=TRUE where account like '%@my.nextcloud';
```

I am only not sure how it can be checked/fixed in some migration.

**Comment by lachmanfrantisek** [comment]
Now, the profile page shows 0 followers, 0 following. (Thats not true.)

I can follow already followed people, but they are not shown in the profile page and I can do this multiple times..

![Snímek z 2019-06-06 09-59-35](https://user-images.githubusercontent.com/20214043/59016980-c96b9200-8842-11e9-8b2a-76e0c434803a.png)
![Snímek z 2019-06-06 09-59-55](https://user-images.githubusercontent.com/20214043/59016643-008d7380-8842-11e9-85f8-475a32fa247e.png)
![Snímek z 2019-06-06 10-00-11](https://user-images.githubusercontent.com/20214043/59016642-008d7380-8842-11e9-9ba7-205fa0371ae5.png)
![Snímek z 2019-06-06 10-00-23](https://user-images.githubusercontent.com/20214043/59016961-c1abed80-8842-11e9-95a5-71c39ac86152.png)
![Snímek z 2019-06-06 10-00-37](https://user-images.githubusercontent.com/20214043/59016640-fff4dd00-8841-11e9-837d-84a0f5c7c7fe.png)

**Comment by daita** [comment]
yes, this was my follow up question: checking the _'accepted'_ field within the _'social_a2_follows'_ table.

**Comment by lachmanfrantisek** [comment]
> yes, this was my follow up question: checking the _'accepted'_ field within the _'social_a2_follows'_ table.

True only for the "new" accounts. What is the meaning of "accepted"? (Who need to accept the following?)

Can I fix the problem with turning them to `TRUE` or is there some federation problem that can be caused by this.

Thank you!

**Comment by daita** [comment]
i will work on a release to fix thoses for old entries

**Comment by lachmanfrantisek** [comment]
OK, thank you.

I change/fix only the `oc_social_a2_cache_actors` table. Do I need to revert these changes to be able to use your fix?

**Comment by daita** [comment]
no

**Comment by daita** [comment]
#584 should fix migrations.

if you want to try the PR:

- `./occ config:app:set --value '0.2.0' social installed_version`
- refresh the page.

**Comment by daita** [comment]
Please confirm issue is fixed in 0.2.5

**Comment by lachmanfrantisek** [comment]
I've updated to `0.2.6` and it looks like it was not solved. I'll play with it tonight more deeply and add some logs/error messages.

**Comment by lachmanfrantisek** [comment]
It looks like the numbers (Follows/Followers) are right, but I cannot follow a new account:

- browser log:
```
Failed to follow user fedoracz@floss.social Error: "Request failed with status code 500"
    exports https://my.nextcloud/apps2/social/js/social.js?v=a08c50b3-9:153
    exports https://my.nextcloud/apps2/social/js/social.js?v=a08c50b3-9:160
    onreadystatechange https://my.nextcloud/apps2/social/js/social.js?v=a08c50b3-9:153
social.js:34:10244
    followAccount https://my.nextcloud/apps2/social/js/social.js?v=a08c50b3-9:34
    o https://my.nextcloud/core/js/dist/main.js?v=a08c50b3-9:230
    H https://my.nextcloud/core/js/dist/main.js?v=a08c50b3-9:230
    u https://my.nextcloud/core/js/dist/main.js?v=a08c50b3-9:235
```
- nextcloud log:
```
[no app in context] Warning: 500 - {"status":-1,"exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","message":"An exception occurred while executing 'INSERT INTO \"oc_social_a2_request_queue\" (\"token\", \"author\", \"activity\", \"instance\", \"priority\", \"status\", \"tries\") VALUES(?, ?, ?, ?, ?, ?, ?)' with params [\"ae6aef61-5602-4995-95a1-314911f8df07\", \"https:\\\/\\\/my.nextcloud\\\/apps\\\/social\\\/@tester\", \"{\\\"@context\\\":[\\\"https:\\\/\\\/www.w3.org\\\/ns\\\/activitystreams\\\"],\\\"id\\\":\\\"https:\\\/\\\/my.nextcloud\\\/1d9870c5-e790-496f-9d96-65ab4646609b\\\",\\\"type\\\":\\\"Follow\\\",\\\"actor\\\":\\\"https:\\\/\\\/my.nextcloud\\\/apps\\\/social\\\/@tester\\\",\\\"object\\\":\\\"https:\\\/\\\/floss.social\\\/users\\\/fedoracz\\\"}\", \"{\\\"uri\\\":\\\"https:\\\/\\\/floss.social\\\/users\\\/fedoracz\\\/inbox\\\",\\\"type\\\":1,\\\"priority\\\":4}\", 4, 0, 0]:\n\nSQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"oc_social_a2_request_queue_pkey\"\nDETAIL:  Key (id)=(14) already exists."}

PUT /apps/social/api/v1/current/follow?account=fedoracz@floss.social
from 172.19.0.6 by tester at 2019-06-27T22:51:48+02:00
```

**Comment by lachmanfrantisek** [comment]
Private messages from the "old" account does not work as well:

```
Failed to create a post 
Object { data: {…}, status: 500, statusText: "Internal Server Error", headers: {…}, config: {…}, request: XMLHttpRequest }
social.js:34:5648
Unhandled promise rejection Error: "Request failed with status code 500"
    exports https://my.nextcloud/apps2/social/js/social.js?v=a08c50b3-9:153
    exports https://my.nextcloud/apps2/social/js/social.js?v=a08c50b3-9:160
    onreadystatechange https://my.nextcloud/apps2/social/js/social.js?v=a08c50b3-9:153
```
```
500 - {"status":-1,"exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","message":"An exception occurred while executing 'INSERT INTO \"oc_social_a2_request_queue\" (\"token\", \"author\", \"activity\", \"instance\", \"priority\", \"status\", \"tries\") VALUES(?, ?, ?, ?, ?, ?, ?)' with params [\"e19b4d8d-1c0e-4811-85b5-cf33e26aa594\", \"https:\\\/\\\/my.nextcloud\\\/apps\\\/social\\\/@scoutadmin\", \"{\\\"@context\\\":[\\\"https:\\\/\\\/www.w3.org\\\/ns\\\/activitystreams\\\",\\\"https:\\\/\\\/w3id.org\\\/security\\\/v1\\\"],\\\"id\\\":\\\"https:\\\/\\\/my.nextcloud\\\/apps\\\/social\\\/@scoutadmin\\\/15616691441231343775\\\/activity\\\",\\\"type\\\":\\\"Create\\\",\\\"actor\\\":\\\"https:\\\/\\\/my.nextcloud\\\/apps\\\/social\\\/@scoutadmin\\\",\\\"object\\\":{\\\"id\\\":\\\"https:\\\/\\\/my.nextcloud\\\/apps\\\/social\\\/@scoutadmin\\\/15616691441231343775\\\",\\\"type\\\":\\\"Note\\\",\\\"published\\\":\\\"2019-06-27T20:59:04+00:00\\\",\\\"local\\\":true,\\\"content\\\":\\\"HI\\\",\\\"attributedTo\\\":\\\"https:\\\/\\\/my.nextcloud\\\/apps\\\/social\\\/@scoutadmin\\\",\\\"inReplyTo\\\":\\\"https:\\\/\\\/my.nextcloud\\\/apps\\\/social\\\/@scoutadmin\\\/1561619151101792876\\\",\\\"sensitive\\\":false},\\\"signature\\\":{\\\"type\\\":\\\"RsaSignature2017\\\",\\\"creator\\\":\\\"https:\\\/\\\/my.nextcloud\\\/apps\\\/social\\\/@scoutadmin#main-key\\\",\\\"created\\\":\\\"2019-06-27T20:59:04Z\\\",\\\"signatureValue\\\":\\\"ohwpVq1M4oaWvmupyTT5rU\\\/v3EfRCQwX18FzF4jh7fOs0X3kJ93Go2U2rxog461ElEEHidPEcgfBeg2KFaB4\\\/0ty7Jld0Z1EYGk64Nd\\\/xZojTDefgaQTM6FBjHNYZaxalyNLIqGZoidR340CUG5zQ6FbFwxSGnRP2LD2g0imPZCir2QdfoRcVdrRTrlWWVfSY+fagAlPWSOopEPpjOr8JU9rlQX4CY1KAICteNw8SzK4b5R8drZDYZL5A12VeEmv+jAFMEqAUlV\\\/DHLgC+fvjCioHb7jKrF7PyI16H0MoaFfyiHxPsNF91ecAr\\\/N0UcSeP+vGLIgTJEwwiY\\\/Xb46ag==\\\"}}\", \"{\\\"uri\\\":\\\"https:\\\/\\\/my.nextcloud\\\/index.php\\\/apps\\\/social\\\/inbox\\\",\\\"type\\\":1,\\\"priority\\\":3}\", 3, 0, 0]:\n\nSQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint \"oc_social_a2_request_queue_pkey\"\nDETAIL: Key (id)=(15) already exists."}
```

**Comment by daita** [comment]
would it be possible to set the `id` field from your table `oc_social_a2_request_queue` to auto-increment ?

**Comment by lachmanfrantisek** [comment]
> would it be possible to set the `id` field from your table `oc_social_a2_request_queue` to auto-increment ?

@daita Excuse my late response. I cannot play with it in the previous days...

I've done some search, but to be honest I am not sure how I can do it right for the postgres.

Current table looks like this:

```
nextcloud=# \d+ oc_social_a2_request_queue
                                                             Table "public.oc_social_a2_request_queue"
  Column  |              Type              | Collation | Nullable |                        Default                         | Storage  | Stats target | Description 
----------+--------------------------------+-----------+----------+--------------------------------------------------------+----------+--------------+-------------
 id       | bigint                         |           | not null | nextval('oc_social_a2_request_queue_id_seq'::regclass) | plain    |              | 
 token    | character varying(63)          |           | not null |                                                        | extended |              | 
 author   | character varying(1000)        |           | not null |                                                        | extended |              | 
 activity | text                           |           | not null |                                                        | extended |              | 
 instance | text                           |           | not null |                                                        | extended |              | 
 priority | smallint                       |           |          | 0                                                      | plain    |              | 
 status   | smallint                       |           |          | 0                                                      | plain    |              | 
 tries    | smallint                       |           |          | 0                                                      | plain    |              | 
 last     | timestamp(0) without time zone |           |          | NULL::timestamp without time zone                      | plain    |              | 
Indexes:
    "oc_social_a2_request_queue_pkey" PRIMARY KEY, btree (id)
```

It has some sequence defined.

**Comment by daita** [comment]
Should have be fixed by now, please re-open this ticket if you still encounter issue
